apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pipeline-grpcurl

resources:
  - ns-pipeline.yaml
  - list-workspace-task.yaml
  - pipeline.yaml
#  - source-pvc.yaml
  - pipeline-run.yaml
#  - update-deployment-task.yaml
