---
apiVersion: v1
kind: Service
metadata:
  name: grpc-with-quarkus-local
spec:
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
    - name: http
      port: 8080
      targetPort: 8080
