kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: idr
  # namespace: app-nees-nui-app
spec:
  host: grpc-with-quarkus.app-nees-nui-app.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: testing
      labels:
        version: v1
    #   trafficPolicy:
    #     portLevelSettings:
    #       - port:
    #           number: 8080
    #         loadBalancer:
    #           simple: ROUND_ROBIN
    # - name: testing
    #   labels:
    #     version: v1
    #   trafficPolicy:
    #     portLevelSettings:
    #       - port:
    #           number: 9000
    #         loadBalancer:
    #           simple: ROUND_ROBIN
