kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: igw
  # namespace: app-nees-nui-app
spec:
  servers:
    - port:
        number: 443
        protocol: HTTPS
        name: https
      hosts:
        - grpc-with-quarkus.app-nees-nui.freubel.sandbox2538.opentlc.com
      tls:
        mode: SIMPLE
        # mode: MUTUAL
        credentialName: igw-app-nees-nui-smcp
  selector:
    istio: ingressgateway

