---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
    - name: app-build
  params:
    - name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
      default: 'main'
    - name: GIT_DIR
      type: string
      default: ""
    - name: IMAGE
      type: string
    - name: CONTAINERFILE
      type: string
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: $(params.GIT_DIR)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: app-build

    # Add an extra step to list the contents of /workspace
    # You might add this before or after another Task
    - name: dump-workspace
      taskRef:
        name: list-workspace
        kind: Task
      workspaces:
        - name: output
          workspace: app-build
      runAfter:
        - fetch-from-git

    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: DOCKERFILE
          value: $(params.CONTAINERFILE)
        - name: CONTEXT
          value: $(params.GIT_DIR)
      workspaces:
        - name: source
          workspace: app-build
      runAfter:
        - dump-workspace
