---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: grpc-with-quarkus
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  name: openjdk-17
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-17
  