---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: b36fec3731fd5384a8351434b4ae6a36ba1ef25b
    app.quarkus.io/build-timestamp: 2023-07-12 - 08:20:58 +0000
  labels:
    app.kubernetes.io/name: grpc-with-quarkus
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: grpc-with-quarkus
spec:
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: grpc-with-quarkus
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  type: ClusterIP