---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: app-cees-cs
  namespace: openshift-ingress-operator
spec:
  domain: app-cees-cs.freubel.sandbox2538.opentlc.com
  namespaceSelector:
    matchLabels:
      type: app-cees-cs
  replicas: 1
  endpointPublishingStrategy:
    loadBalancer:
      scope: External
      # scope: Internal
    type: LoadBalancerService
    