apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: grpc-with-quarkus
  version: v1

resources:
- ic-app-cees-bcu.yaml # app-cees-bcu.freubel.sandbox2538.opentlc.com
- ic-app-cees-cs.yaml  # app-cees-cs.freubel.sandbox2538.opentlc.com
# - ic-app-cees.yaml     # app-cees.freubel.sandbox2538.opentlc.com
- ic-app-nees-nui.yaml # app-nees-nui.freubel.sandbox2538.opentlc.com

