---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-maven-m2-cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

