apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: grpcurl
      version: v1.87 # TODO: version
    # app.openshift.io/vcs-uri: "https://github.com/buuhsmead/grpcurl.git"
    # app.openshift.io/vcs-url: "https://github.com/buuhsmead/grpcurl.git"

resources:
  - deployment.yaml
